In [844]:
"""
Default for to go is to go?
default for milks is milk
"""

'\nDefault for to go is to go?\ndefault for milks is milk\n'

In [845]:
import pandas as pd # helpful imports
import numpy as np
import plotly.express as px

#np.set_printoptions(threshold=1000)
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None) # shows all columns

In [846]:
# importing all the data from 2019 to probably april 5 2026 1:05 PM
sales2019 = pd.read_csv("item2019-2020.csv")
sales2020 = pd.read_csv("item2020-2021.csv")
sales2021 = pd.read_csv("item2021-2022.csv")
sales2022 = pd.read_csv("item2022-2023.csv")
sales2023 = pd.read_csv("item2023-2024.csv")
sales2024 = pd.read_csv("item2024-2025.csv")
sales2025 = pd.read_csv("item2025-2026.csv")

In [847]:
sales2025.head() # checking the date and all the columns

,Date,Time,Time Zone,Category,Item,Qty,Price Point Name,SKU,Modifiers Applied,Gross Sales,Discounts,Net Sales,Tax,Transaction ID,Payment ID,Device Name,Notes,Details,Event Type,Location,Dining Option,Customer ID,Customer Name,Customer Reference ID,Unit,Count,Itemization Type,Fulfillment Note,Channel,Token,Card Brand,PAN Suffix
0,2026-04-05,13:05:34,Central Time (US & Canada),Merch,Pullover,1.0,Regular,NaN,Medium,$30.00,$0.00,$30.00,$0.00,WCdzxV98P1EBjoWFeNOhFGnxEGJZY,vVZNyXwZtGWYLIsHn0qE2E6UiZUZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,FTO424PFVBNV5P7N5BXLECDE,American Express,2002
1,2026-04-05,12:20:41,Central Time (US & Canada),Merch,Cap,1.0,Regular,NaN,NaN,$15.00,$0.00,$15.00,$0.00,GOtQuPyOjxZ9lWdAz9QqirhK9wUZY,Xt5guot0xr3Si9hYiFro4I1He8XZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,KODAURC2A3JCGWX7RI7JBZEA,Visa,0899
2,2026-04-05,12:20:05,Central Time (US & Canada),Merch,Cap,1.0,Regular,NaN,NaN,$15.00,$0.00,$15.00,$0.00,EfIR0ENM42iS3ZLjh6LNJdxWpOHZY,TP9xgFcRTqz8lWHplocvezmsq18YY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,KODAURC2A3JCGWX7RI7JBZEA,American Express,5001
3,2026-04-02,15:58:21,Central Time (US & Canada),Food,LiaP Cookie,1.0,Regular,NaN,NaN,$2.00,$0.00,$2.00,$0.00,akf0nu5TgcGa6Pfl7WJ0hWK2K9VZY,xGN9FCuruBTGZilUtpmWNeK9ynMZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,X3USJTW3R3XBVQU2ZAUPEW6L,Visa,0050
4,2026-04-02,15:50:23,Central Time (US & Canada),Espresso Drinks,Cappuccino,1.0,Regular,NaN,"Regular, To go, Whole, Ube",$5.25,$0.00,$5.25,$0.00,gP9FNsHXWcOUbaTgxH0En2ZJIabZY,HBfQwmaKDyw2rQ6eCMgNccRz9uaZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,ZEVMUUXK3J3HJ62R53FYRMDN,Visa,7376

In [848]:
sales = pd.concat([sales2019, sales2020, sales2021, sales2022, sales2023, sales2024, sales2025], ignore_index=True) # combining all the sales data together
sales.shape # There is 49806 points of data

(49806, 32)

In [849]:
sales.head()

,Date,Time,Time Zone,Category,Item,Qty,Price Point Name,SKU,Modifiers Applied,Gross Sales,Discounts,Net Sales,Tax,Transaction ID,Payment ID,Device Name,Notes,Details,Event Type,Location,Dining Option,Customer ID,Customer Name,Customer Reference ID,Unit,Count,Itemization Type,Fulfillment Note,Channel,Token,Card Brand,PAN Suffix
0,2020-05-09,11:10:24,Central Time (US & Canada),Drinks,Latte,1.0,Regular,NaN,NaN,$3.00,$0.00,$3.00,$0.00,orJGaJC50EssZL75PdNmI49eV,NCSwfIZBqz0bZOig70dWDbgLvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,2NWJE4878X5AX1J2HP3QR3PYPR,Madeline Nowak,NaN,ea,1,Physical Good,NaN,NaN,VWPCBBUZB7VCAFGTJWK4GKWN,Visa,6073.0
1,2020-05-09,11:09:45,Central Time (US & Canada),Drinks,Latte,1.0,Regular,NaN,NaN,$3.00,$0.00,$3.00,$0.00,iSyafDYub6ZtNv9htZNhKrpeV,w1W7QW3n1UH3sx11u9RuKQB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,NaN,VWPCBBUZB7VCAFGTJWK4GKWN,NaN,NaN
2,2020-03-11,14:55:19,Central Time (US & Canada),Drinks,Coffee,1.0,Regular,NaN,NaN,$2.00,$0.00,$2.00,$0.00,ELE9rssYcA12gouEXOA2us4eV,JGd4Bcl470EPFNVhPlcjQMCCwaB,iPad,12 oz Drip Coffee,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,4079DCZCJS6X32R23131S5K63G,Monica Mackie,NaN,ea,1,Physical Good,NaN,NaN,5H2VGAOSSRFG3N3AZA4CGBAB,Visa,5240.0
3,2020-03-11,12:52:54,Central Time (US & Canada),Drinks,Coffee,1.0,Regular,NaN,NaN,$2.00,$0.00,$2.00,$0.00,UrgTE9EiIM0Zcklh4zWCmz6eV,3VF4W0eeorL4Z0C43CqiJkIcuaB,iPad,12 oz Drip Coffee,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,K6VN87C31EK8YEPVT1TKYVBDDR,Aida Pavello,NaN,ea,1,Physical Good,NaN,NaN,5H2VGAOSSRFG3N3AZA4CGBAB,MasterCard,5879.0
4,2020-03-10,15:26:46,Central Time (US & Canada),Drinks,Tea,1.0,Regular,NaN,NaN,$3.00,$0.00,$3.00,$0.00,EjQr2w7zLb2CxBFpuPaLqs4eV,90tj7laoKyTwHDh2RjPsEQCwvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,9Z5YV76DP137Z8N3K955AZ2DR4,Pratish Shinde,NaN,ea,1,Physical Good,NaN,NaN,D78EA7BB-B863-43AC-B95F-0D4DD2E6C8C4,Visa,9179.0

In [850]:
sales[sales['Category'] != 'Drinks']

,Date,Time,Time Zone,Category,Item,Qty,Price Point Name,SKU,Modifiers Applied,Gross Sales,Discounts,Net Sales,Tax,Transaction ID,Payment ID,Device Name,Notes,Details,Event Type,Location,Dining Option,Customer ID,Customer Name,Customer Reference ID,Unit,Count,Itemization Type,Fulfillment Note,Channel,Token,Card Brand,PAN Suffix
13,2020-03-09,14:59:16,Central Time (US & Canada),NaN,Almond Milk,1.0,Regular,NaN,NaN,$1.00,$0.00,$1.00,$0.00,81PVQ5yOODaN6ycBqTsZbnzeV,C26n2FMzOPaBMLXZVSZ8KQB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,NaN,NaN
20,2020-03-05,15:09:33,Central Time (US & Canada),NaN,Almond Milk,1.0,Regular,NaN,NaN,$1.00,$0.00,$1.00,$0.00,cf28n6RCRaO0RkZadFmODO6eV,pMQQTggw0yMEGJr3O7UKbWVFuaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,YQGQFC6SYX5C30XRSGN9PY2340,Rosalinda Rodriguez,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,Visa,6527.0
22,2020-03-05,15:09:33,Central Time (US & Canada),NaN,Almond Milk,1.0,Regular,NaN,NaN,$1.00,$0.00,$1.00,$0.00,cf28n6RCRaO0RkZadFmODO6eV,pMQQTggw0yMEGJr3O7UKbWVFuaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,YQGQFC6SYX5C30XRSGN9PY2340,Rosalinda Rodriguez,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,Visa,6527.0
25,2020-03-05,14:30:50,Central Time (US & Canada),NaN,Almond Milk,1.0,Regular,NaN,NaN,$1.00,$0.00,$1.00,$0.00,UPoOm4pP0o4im0JDJxGyKAoeV,ewKwS86Fc1yVBZG9RZ0dLQB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,NaN,NaN
32,2020-03-03,14:17:34,Central Time (US & Canada),NaN,Vanilla Flavor,1.0,Regular,NaN,NaN,$1.00,$0.00,$1.00,$0.00,oP7qk5Efz5WzaeVfhp5kQPkeV,5q7knpQP1hLNzwjMGeDk2GVHuaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,PJG6SDA3P95WK9APC28JQ0KTQ8,Valeria Apodaca,NaN,ea,1,Physical Good,NaN,NaN,22E0EDAF-DDED-43B2-83E6-28634DAC6304,Visa,7562.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49801,2025-08-25,09:03:23,Central Time (US & Canada),Coffee Drinks,Coffee,1.0,Regular,NaN,Here,$3.00,$0.00,$3.00,$0.00,ExLsX6jjz3fi8isFZQs9oPQekFUZY,bpkr0EyXmi9nRgDpw3DiGQcwt1MZY,iPad,12 oz Drip Coffee,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,5H2VGAOSSRFG3N3AZA4CGBAB,Visa,0120
49802,2025-08-01,14:40:40,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$1.00,$0.00,$1.00,$0.00,0TksSijtrCzHygWt9urwDdp9ocbZY,jTxi5owu5N7TT2dD4tKulvyVmcOZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,X5907T36XH2JQBJEE3VG5ZJPVG,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,MasterCard,2703
49803,2025-08-01,14:37:43,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$1.00,$0.00,$1.00,$0.00,iiseOfyTSj87eQacT348ck8NKYSZY,br5VgUBThGjCCyOlvfTNh3xh1WXZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,X5907T36XH2JQBJEE3VG5ZJPVG,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,MasterCard,2703
49804,2025-08-01,14:35:09,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$1.00,$0.00,$1.00,$0.00,Kg3FITeONv7CDWHWGQmvUNIPOhYZY,DjhgOhl2WojyQMYsmbMMbYOzwSAZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,X5907T36XH2JQBJEE3VG5ZJPVG,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,MasterCard,2703
49805,2025-08-01,14:32:13,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$1.00,$0.00,$1.00,$0.00,Mjm0CevnyxLya6FLpR06sPpXrRKZY,li8C6nU83eyip7Kiw7bX8JJya8IZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,X5907T36XH2JQBJEE3VG5ZJPVG,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,MasterCard,2703

In [851]:
sales[(sales['Token'] == 'GMD53HVCBKGZVCBX5FMT5JXX') & sales['Customer Name'].notnull()] 
# Looks like Token is card info encripted by square 
# This particular card looks like it was shared amoung the early staff/mishes

,Date,Time,Time Zone,Category,Item,Qty,Price Point Name,SKU,Modifiers Applied,Gross Sales,Discounts,Net Sales,Tax,Transaction ID,Payment ID,Device Name,Notes,Details,Event Type,Location,Dining Option,Customer ID,Customer Name,Customer Reference ID,Unit,Count,Itemization Type,Fulfillment Note,Channel,Token,Card Brand,PAN Suffix
20,2020-03-05,15:09:33,Central Time (US & Canada),NaN,Almond Milk,1.0,Regular,NaN,NaN,$1.00,$0.00,$1.00,$0.00,cf28n6RCRaO0RkZadFmODO6eV,pMQQTggw0yMEGJr3O7UKbWVFuaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,YQGQFC6SYX5C30XRSGN9PY2340,Rosalinda Rodriguez,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,Visa,6527.0
22,2020-03-05,15:09:33,Central Time (US & Canada),NaN,Almond Milk,1.0,Regular,NaN,NaN,$1.00,$0.00,$1.00,$0.00,cf28n6RCRaO0RkZadFmODO6eV,pMQQTggw0yMEGJr3O7UKbWVFuaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,YQGQFC6SYX5C30XRSGN9PY2340,Rosalinda Rodriguez,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,Visa,6527.0
66,2020-02-23,11:57:36,Central Time (US & Canada),NaN,Almond Milk,1.0,Regular,NaN,NaN,$1.00,$0.00,$1.00,$0.00,on1hQp7aRBw8rVBsEahMFkyeV,vzcj03lJaeb5HOwQ8iNrG4DMvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,SCEX9Y7E7D1B7ESGMV2439WQM8,Sarah Karstrand,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,Visa,1230.0
130,2020-02-10,10:16:40,Central Time (US & Canada),NaN,Almond Milk,1.0,Regular,NaN,NaN,$1.00,$0.00,$1.00,$0.00,sjM0pOYG9g4qbTMPILsPuf1eV,vJnXOVMtp8m0hJRmWJ1dCunBvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,VSTNBPAG955DV7DBW50QVF7W2W,Xavier Meyer,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,MasterCard,8623.0
234,2020-01-16,11:03:30,Central Time (US & Canada),NaN,Almond Milk,1.0,Regular,NaN,NaN,$1.00,$0.00,$1.00,$0.00,26itw7MUdedC0PTvOEwiotheV,xgiDUdsokob2MiQ7ystIP39SvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,V7SM68XJ4ZW6D67B62G0A7WQ6M,Alexander Campillanos,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,Visa,1685.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4932,2021-08-31,09:04:22,Central Time (US & Canada),Extras,Almond Milk,1.0,Regular,NaN,NaN,$0.75,$0.00,$0.75,$0.00,onB3eCIP0of3QRB3xOnJRHveV,H7e9aQA51h7SMbuEbIYJvbxluaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,PMPS3SY62H67S74B8GHB3YKE84,Olivia Ahlberg,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,MasterCard,4303.0
4935,2021-08-30,13:18:21,Central Time (US & Canada),Extras,Almond Milk,1.0,Regular,NaN,NaN,$0.75,$0.00,$0.75,$0.00,oXZX20D8d30zPUsRqGv3HM2eV,fzQ3IexmMrvhPAHCS6zGEwCQuaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,FKVY22HM4X7G9136RQX72VBNF0,Daniel Enriquez,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,Visa,444.0
4941,2021-08-30,11:13:46,Central Time (US & Canada),Extras,Almond Milk,1.0,Regular,NaN,NaN,$0.75,$0.00,$0.75,$0.00,KEhld9SWgCHoGIpbh2QbPTlBr0EZY,huZBM9vV6Zd9MlgNQE3daQpeekcZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,ZV5YCPXC6D0F3115Y9W7ZD0EJ8,Vivienne Lato,NaN,ea,1,Physical Good,NaN,Cor Coffee,GMD53HVCBKGZVCBX5FMT5JXX,Visa,8111.0
4995,2021-08-26,09:06:30,Central Time (US & Canada),Extras,Almond Milk,1.0,Regular,NaN,NaN,$0.75,$0.00,$0.75,$0.00,COq10PXHB2FJIyqZrYVAQ28eV,d0zwqrVnQ8NZYlPq9WGlcmLYuaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,ZV5YCPXC6D0F3115Y9W7ZD0EJ8,Vivienne Lato,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,Visa,8111.0
5014,2021-08-25,09:52:14,Central Time (US & Canada),Extras,Almond Milk,1.0,Regular,NaN,NaN,$0.75,$0.00,$0.75,$0.00,IVsLZEKer9W9DSwlL2PDQFoeV,1i4sdSUrvRQlyyNlamXcFsKevaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,ZYC0ATENXX3CD8TA6A5985ENNC,jamie.taberna@focus.org,NaN,ea,1,Physical Good,NaN,NaN,GMD53HVCBKGZVCBX5FMT5JXX,Visa,7975.0

In [852]:
sales[sales['SKU'].notnull()]
# all of these columns are NaN

Empty DataFrame
Columns: [Date, Time, Time Zone, Category, Item, Qty, Price Point Name, SKU, Modifiers Applied, Gross Sales, Discounts, Net Sales, Tax, Transaction ID, Payment ID, Device Name, Notes, Details, Event Type, Location, Dining Option, Customer ID, Customer Name, Customer Reference ID, Unit, Count, Itemization Type, Fulfillment Note, Channel, Token, Card Brand, PAN Suffix]
Index: []

In [853]:
sales['Price Point Name'].unique() # regular means drinks, red means tshirt, PB Chocolate + Butter Scotch means a bar one time, Toasted Coconut + Vanilla Bean means bar one time, Graphite means t shirt, 29 NAN these were all before Cor started
#print(len(sales[sales['Price Point Name'].isna()])) #29 NA
sales[sales['Price Point Name'].isna()] # I can successfully frop Price Point since its of no use to me

,Date,Time,Time Zone,Category,Item,Qty,Price Point Name,SKU,Modifiers Applied,Gross Sales,Discounts,Net Sales,Tax,Transaction ID,Payment ID,Device Name,Notes,Details,Event Type,Location,Dining Option,Customer ID,Customer Name,Customer Reference ID,Unit,Count,Itemization Type,Fulfillment Note,Channel,Token,Card Brand,PAN Suffix
473,2019-11-11,11:48:01,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$3.00,$0.00,$3.00,$0.00,eklDZZ1YVvwVww3UEXVmxPheV,OBkXF18ZT4lDlpsKKWqpTsMF,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,VCVA2WC4YD48D490C72NJPCJMG,NaN,NaN,ea,1,NaN,NaN,NaN,NaN,American Express,1004.0
1027,2022-04-13,09:29:42,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$1.00,$0.00,$1.00,$0.00,w54dXBNXMVtYH3vy4A4TNtneV,j10rTnZ4carwY7gLaMLIAuzmvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,5J2CSYCNHS2W19SQADJ803DC7W,Saul Ortiz,NaN,ea,1,NaN,NaN,NaN,NaN,MasterCard,1636.0
3461,2021-11-10,14:20:21,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$1.50,$0.00,$1.50,$0.00,G2tdKuTDJ9Hyym55aG5Bue4eV,rzb4jPSU5yr02pUPHycimuL5vaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,5AH1ME5W9D1AB2HZNVPXFRCQPR,Juancarlos Paez,NaN,ea,1,NaN,NaN,NaN,NaN,Discover,8031.0
4259,2021-10-01,14:26:13,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$20.00,$0.00,$20.00,$0.00,GcIcGz0awHT4wWfzJyE0p5HIpRRZY,NwbPALRJkEV0WDZtjq8PZee6eWaZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,7V11NB7R6N2YVC68BJ58NMFNPC,Claire Danstrom,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,6032.0
4430,2021-09-24,15:05:45,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$2.00,$0.00,$2.00,$0.00,aY5EKojciIJYXlEmFa4H94HY7iWZY,dSctOnoto3RsJVyjIMmhsI3iC7DZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,SM1X1WAAB55573BXC8BWGMQ1J0,Kirk Tejas,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,1154.0
4431,2021-09-24,14:43:14,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$2.00,$0.00,$2.00,$0.00,oT1rrH2r8CyPQSEmVn0IUXHW2JWZY,toDjdfNq3HmxYoCoA8TyH2ABNx9YY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,TV30AQ5P7N1N7E4TW1Y1NNRNYW,Queen Chanelle Parcon,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,5450.0
8353,2022-12-10,11:34:59,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$5.00,$0.00,$5.00,$0.00,E9tS0PF1CYOSfDBF6japVBGon0GZY,RAgSWPIx3X77fFS8YqEQR9iJ82TZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,2152.0
8354,2022-12-10,10:34:51,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$5.25,$0.00,$5.25,$0.00,kN7hWS1vM3kmkn9xB8k71I3RVJRZY,DNaymdjfI7BB2MJP2ZsMKcBbiodZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,MasterCard,2397.0
8355,2022-12-10,10:04:45,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$6.00,$0.00,$6.00,$0.00,EZPwkO30edYQtSpGtCA3VjdaRhbZY,jLTnGwZhgKURvNeozPRjiJFMg3QZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,YKPK5T9QSX0NN4K269Q8221AQ4,Claire Dougherty,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,2681.0
8356,2022-12-10,10:00:55,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$7.00,$0.00,$7.00,$0.00,yOWwiKBPyB6KNl0X0LFfI9EbudKZY,BY2N2LDmfTdZr3EzOBDvFH3v8KYZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,2149.0
8357,2022-12-10,10:00:31,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$7.00,$0.00,$7.00,$0.00,msksN0pJMOxQyYPHPSsvtM1GAH9YY,VsX7UEeBxgNPvg9uzY4QV4BzcxTZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,NaN,NaN
8358,2022-12-10,09:52:36,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$2.50,$0.00,$2.50,$0.00,2KRlb7IoOOCUzhckTjRNpG7EOvLZY,xEaANPoNsZ6Rkq7krSZIOzJoeaKZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,MasterCard,4258.0
8359,2022-12-10,09:46:00,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$4.50,$0.00,$4.50,$0.00,aAXLPgWzBzww7V0qt92YWVsqqiIZY,JgoLvG5bypz9r3Kkw4ZPDk9UXu9YY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,WWGSZVEGEX5H769NSY52WPC8B8,Bridget Mcmillan,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,MasterCard,8135.0
8360,2022-12-10,09:45:02,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$5.75,$0.00,$5.75,$0.00,I3lAuML2gSaILBdCOm5S2aFivVGZY,dyGykiRW4rLcsGvdcCkYw0lQXqfZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,2152.0
8361,2022-12-10,09:40:04,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$5.00,$0.00,$5.00,$0.00,0HQDE47SImu3qBSNREf5zSnhYFBZY,TJqBCACTpAfkg5Cr5z3WoJGoUqXZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,A145QDSBG94MK21PET1AP4MS0W,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,5464.0
8362,2022-12-10,09:39:17,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$4.50,$0.00,$4.50,$0.00,wBahUKDFr2Qx2OrAcrLyvT0P3KKZY,jtMrC8ELxkb4cq6oEoBKHZqPYKaZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,4977.0
8363,2022-12-10,09:38:17,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$4.50,$0.00,$4.50,$0.00,kFHx64yMtPqIozdurmqGK05E5iEZY,f9L6qPk0qd3iBrRSyqho03ttJl7YY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,QSWK3QXRB51D78738GP0CCF7PW,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,1725.0
8364,2022-12-10,09:37:37,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$5.00,$0.00,$5.00,$0.00,YTZDrFsskrAyCjGLqISuI5o0g5KZY,jVyefWthbNyLAz5lOaJWqsFfCwXZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,6268.0
8365,2022-12-10,09:34:00,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$2.50,$0.00,$2.50,$0.00,2Sh3zkCDnL0Fl4HLdP0PjGAUdnTZY,x6z7jtdmmpninFVMC0ybe18rxmPZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,K3M4J3JYBS6CFBK1S1HXQCNZTM,Lydia Schaecher,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,6448.0
8366,2022-12-10,09:32:59,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$4.00,$0.00,$4.00,$0.00,moWwSkFdkOr2dyN5F7pHiC3q8kPZY,hYevlA30kv2pl0CPKCtaAuThy0aZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,QWWQ31FFTS5QF4108GHWY891DC,Natalie Robertson,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,4006.0
9699,2022-10-20,10:00:56,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$5.00,$0.00,$5.00,$0.00,8PeDxiUwnktVqF1KcuOCJX9tkHLZY,vrOiOfr1t4WJQmpRAumcOtA8sX9YY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,1177.0
11188,2022-08-31,14:02:06,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$1.00,$0.00,$1.00,$0.00,usQNKMPHNMipR47FRA11wqnZtcdZY,xkkzScC8nikb8cmZRr14OmiiaQVZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,5797.0
11199,2022-08-31,12:45:54,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$1.00,$0.00,$1.00,$0.00,ekyAlFFFk9cZ4bc8lIixadFlL6MZY,PNBzeKX2J3yZ4XPcqVkMQJwTJURZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,QT31HTABFS7TX3QY0RAR4BW05G,Edgar Viveros,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,191.0
42485,2025-11-24,15:04:37,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$5.25,$0.00,$5.25,$0.00,Wmf74rWNdFsaKGQuZH0COhBeKM7YY,5a9Z5eobn4On2tgMTxnxDowT6SUZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,DHTGGS3ZJ23DECJK8PY66J8RZG,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,MasterCard,9028
42487,2025-11-24,14:55:26,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$5.25,$0.00,$5.25,$0.00,mki7WNr6gBcArQKn9DcAsBVc8XdZY,92YmCj9PicgN4vJM2ksRfOPGI0bZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,Visa,0280
49802,2025-08-01,14:40:40,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$1.00,$0.00,$1.00,$0.00,0TksSijtrCzHygWt9urwDdp9ocbZY,jTxi5owu5N7TT2dD4tKulvyVmcOZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,X5907T36XH2JQBJEE3VG5ZJPVG,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,MasterCard,2703
49803,2025-08-01,14:37:43,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$1.00,$0.00,$1.00,$0.00,iiseOfyTSj87eQacT348ck8NKYSZY,br5VgUBThGjCCyOlvfTNh3xh1WXZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,X5907T36XH2JQBJEE3VG5ZJPVG,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,MasterCard,2703
49804,2025-08-01,14:35:09,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$1.00,$0.00,$1.00,$0.00,Kg3FITeONv7CDWHWGQmvUNIPOhYZY,DjhgOhl2WojyQMYsmbMMbYOzwSAZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,X5907T36XH2JQBJEE3VG5ZJPVG,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,MasterCard,2703
49805,2025-08-01,14:32:13,Central Time (US & Canada),NaN,Custom Amount,1.0,NaN,NaN,NaN,$1.00,$0.00,$1.00,$0.00,Mjm0CevnyxLya6FLpR06sPpXrRKZY,li8C6nU83eyip7Kiw7bX8JJya8IZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,X5907T36XH2JQBJEE3VG5ZJPVG,NaN,NaN,ea,1,NaN,NaN,Cor Coffee,NaN,MasterCard,2703

In [854]:
sales = sales.dropna(subset=['Price Point Name'])

In [855]:
#Checking customer ID 
#sales['Customer ID'].isna().sum() # There are 26,696 NA out of 49777 obs ~ roughly 53.63% present data
#print(26696/49777) # Lowkey not helpful indicater neither is 


sales['Customer Reference ID'].notna().sum() # only 21 not null which is extremly unhelpful lowk

np.int64(21)

In [856]:
sales['Transaction ID'].unique 
# Basically every transaction has an ID so this is an unhelpful identifier and I likely won't use this

<bound method Series.unique of 0            orJGaJC50EssZL75PdNmI49eV
1            iSyafDYub6ZtNv9htZNhKrpeV
2            ELE9rssYcA12gouEXOA2us4eV
3            UrgTE9EiIM0Zcklh4zWCmz6eV
4            EjQr2w7zLb2CxBFpuPaLqs4eV
                     ...
49797    EH4ZBKoBRk8g2R1IbrHhzTlRLbSZY
49798    EH4ZBKoBRk8g2R1IbrHhzTlRLbSZY
49799    eUGcpL5d1lxoPyOJVlmAFoGaoMJZY
49800    eUGcpL5d1lxoPyOJVlmAFoGaoMJZY
49801    ExLsX6jjz3fi8isFZQs9oPQekFUZY
Name: Transaction ID, Length: 49777, dtype: str>

In [857]:
sales['Payment ID'].unique # same thing as transaction ID lowkey don't want this

<bound method Series.unique of 0          NCSwfIZBqz0bZOig70dWDbgLvaB
1              w1W7QW3n1UH3sx11u9RuKQB
2          JGd4Bcl470EPFNVhPlcjQMCCwaB
3          3VF4W0eeorL4Z0C43CqiJkIcuaB
4          90tj7laoKyTwHDh2RjPsEQCwvaB
                     ...
49797    VA15O40Ewb16csONcM3hRnP8WN7YY
49798    VA15O40Ewb16csONcM3hRnP8WN7YY
49799    DBww08vkb0651rDlp8g8fy0OQz9YY
49800    DBww08vkb0651rDlp8g8fy0OQz9YY
49801    bpkr0EyXmi9nRgDpw3DiGQcwt1MZY
Name: Payment ID, Length: 49777, dtype: str>

In [858]:
sales[sales['Unit'] != 'ea'] # Every Row is Ea

Empty DataFrame
Columns: [Date, Time, Time Zone, Category, Item, Qty, Price Point Name, SKU, Modifiers Applied, Gross Sales, Discounts, Net Sales, Tax, Transaction ID, Payment ID, Device Name, Notes, Details, Event Type, Location, Dining Option, Customer ID, Customer Name, Customer Reference ID, Unit, Count, Itemization Type, Fulfillment Note, Channel, Token, Card Brand, PAN Suffix]
Index: []

In [859]:
sales['Channel'].unique() # Almost every Channel is Cor Coffee so not helpful

array([nan, 'Cor Coffee'], dtype=object)

In [860]:
#sales['Token'].unique() # There are 67 unique tokens? 
#sales['Token'].isna().sum() # Returned 0 so all rows have tokens

sales[sales['Customer Name'].str.contains("David Kranenburg")]['Token'].unique() 
# I thought that Token was a column that took a payment card and tokenized it but it looks like david has about 16 unique tokens which doesn't make sense

#sales[(sales['Token'] == 'CXWFYM5AJSZBDVR6PCR4NO56') & ~(sales['Item'].str.contains("lem", case= False))]
sales[ (sales['Token'] == 'CXWFYM5AJSZBDVR6PCR4NO56') & sales['Item'].str.contains("lem", case= False) ]['Item'].unique() # Theres only Lavlem and Lemonade for this Token

#Hypothesis: I think Token is related to keywords in Items

sales.groupby('Token')['Item'].nunique().value_counts()

""" 
Item
1    55
2    11
4     1
"""
sales[sales['Token'] == sales.groupby('Token')['Item'].nunique().idxmax()]['Item'].unique()

# Token actyally is useful because it gives VERY consistent item type despite spelling and case

<ArrowStringArray>
['Hot chocolate', 'Hot Chocolate', 'Hot Chocolate ', 'Hot Cocoa']
Length: 4, dtype: str

In [861]:
sales[sales['Fulfillment Note'].notna()] # is all NA

Empty DataFrame
Columns: [Date, Time, Time Zone, Category, Item, Qty, Price Point Name, SKU, Modifiers Applied, Gross Sales, Discounts, Net Sales, Tax, Transaction ID, Payment ID, Device Name, Notes, Details, Event Type, Location, Dining Option, Customer ID, Customer Name, Customer Reference ID, Unit, Count, Itemization Type, Fulfillment Note, Channel, Token, Card Brand, PAN Suffix]
Index: []

In [862]:
sales['Itemization Type'].unique() # All just physical good we can get rid of this

<ArrowStringArray>
['Physical Good']
Length: 1, dtype: str

In [863]:
sales['Category'].unique()

"""
'Drinks',               nan, 'Espresso Drinks',          'Extras',
   'Coffee Drinks',            'Teas',            'Food',           'Merch',
    'Other Drinks'
"""
sales[sales['Category'] == "Teas"] # Ill keep around since it can be a classifer for teas

,Date,Time,Time Zone,Category,Item,Qty,Price Point Name,SKU,Modifiers Applied,Gross Sales,Discounts,Net Sales,Tax,Transaction ID,Payment ID,Device Name,Notes,Details,Event Type,Location,Dining Option,Customer ID,Customer Name,Customer Reference ID,Unit,Count,Itemization Type,Fulfillment Note,Channel,Token,Card Brand,PAN Suffix
508,2022-05-06,13:20:10,Central Time (US & Canada),Teas,Chai Latte,1.0,Regular,NaN,NaN,$4.50,-$2.25,$2.25,$0.00,0XIuXZ10SDQPzVRubimHVe2eV,1Sogn9Y6ep6zlraqQis0xmowuaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,NaN,CWYPJ36L3V2WQDT4R4ADZDS3,MasterCard,999.0
517,2022-05-06,09:13:40,Central Time (US & Canada),Teas,Iced Chai Latte,1.0,Regular,NaN,NaN,$4.50,-$4.50,$0.00,$0.00,uAWcEbiQPh3TQL6JjwMig90eV,3xhLggvCVR8Iy0REOEmbygGVvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,NaN,3NBMLPETQXRBMX2WLORWW57I,NaN,NaN
521,2022-05-06,09:11:17,Central Time (US & Canada),Teas,Iced Chai Latte,1.0,Regular,NaN,NaN,$4.50,-$2.25,$2.25,$0.00,oFYXmlfT8h2tgCaXPbybEToeV,Fsv5i2aZNooTLRdJ8CdOdSIxuaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NJVS4XCS1X27X4DGNCBAAPX9FR,Mira Azar,NaN,ea,1,Physical Good,NaN,NaN,3NBMLPETQXRBMX2WLORWW57I,Visa,9441.0
529,2022-05-05,14:57:54,Central Time (US & Canada),Teas,Iced Chai Latte,1.0,Regular,NaN,NaN,$4.50,-$2.25,$2.25,$0.00,qWWOKQcCozuwaafOoDbqsXmeV,1aOx3R2uI5fxpr3ThOSDEJHZuaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,VEDBXX3B0H3P3BYT479Y073ZDG,Bogumila Starzycka,NaN,ea,1,Physical Good,NaN,NaN,3NBMLPETQXRBMX2WLORWW57I,Visa,728.0
591,2022-05-02,15:20:59,Central Time (US & Canada),Teas,Chai Latte,1.0,Regular,NaN,NaN,$4.50,-$2.25,$2.25,$0.00,u02HmoVYvH1agbk8WZm0GQheV,Ry92h6l3PiRaxih1oealgOaluaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,NaN,CWYPJ36L3V2WQDT4R4ADZDS3,Visa,7108.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49784,2025-08-25,09:52:31,Central Time (US & Canada),Teas,Matcha Latte,1.0,Regular,NaN,"To go, Iced, Oat, Vanilla, Regular",$6.50,$0.00,$6.50,$0.00,eWHCaivpfPXzog6DrWsyTPFz7rdZY,vnwwukFfV3SWCfJTpUx9U0j85IEZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,G7P3NZP685T2RYFPZR85S34380,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,MWGA4DJR7A2O6CONTZDV4CUM,MasterCard,3849
49790,2025-08-25,09:38:00,Central Time (US & Canada),Teas,Matcha Latte,1.0,Regular,NaN,"To go, Iced, Almond, Vanilla, Regular",$6.50,$0.00,$6.50,$0.00,YJySOSux0VbsfeAqzOT1fCKci8PZY,r1MUvi9Fwer2nOvrcBPHkUbKO8TZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,MWGA4DJR7A2O6CONTZDV4CUM,Visa,9205
49791,2025-08-25,09:38:00,Central Time (US & Canada),Teas,Matcha Latte,1.0,Regular,NaN,"To go, Iced, Almond, Vanilla, Regular",$6.50,-$6.50,$0.00,$0.00,YJySOSux0VbsfeAqzOT1fCKci8PZY,r1MUvi9Fwer2nOvrcBPHkUbKO8TZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,MWGA4DJR7A2O6CONTZDV4CUM,Visa,9205
49792,2025-08-25,09:35:26,Central Time (US & Canada),Teas,Matcha Latte,1.0,Regular,NaN,"To go, Iced, Whole, Vanilla, Regular",$5.75,-$5.75,$0.00,$0.00,6OggYcCZNcXcCm3cXDXCuP9Du5RZY,54gp2bmhvWi8FNzSBFMzKnfRDiVZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,MWGA4DJR7A2O6CONTZDV4CUM,NaN,NaN
49797,2025-08-25,09:17:25,Central Time (US & Canada),Teas,London Fog,1.0,Regular,NaN,To go,$4.50,$0.00,$4.50,$0.00,EH4ZBKoBRk8g2R1IbrHhzTlRLbSZY,VA15O40Ewb16csONcM3hRnP8WN7YY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,ASBUJQPAKB7PKDAKBRL7NY6M,Discover,6329

In [864]:
sales['Discounts'].unique() # Not sure what discounts is but theres a bunch of data for it
sales['Discounts'].isna().sum() #  There are no Nas

sales[sales['Discounts'] !=  "$0.00"] # Discounts account for the change between gross sales and net sales not super helpful but I can keep it around for now

,Date,Time,Time Zone,Category,Item,Qty,Price Point Name,SKU,Modifiers Applied,Gross Sales,Discounts,Net Sales,Tax,Transaction ID,Payment ID,Device Name,Notes,Details,Event Type,Location,Dining Option,Customer ID,Customer Name,Customer Reference ID,Unit,Count,Itemization Type,Fulfillment Note,Channel,Token,Card Brand,PAN Suffix
495,2022-05-06,15:57:49,Central Time (US & Canada),Espresso Drinks,Iced Americano,1.0,Regular,NaN,NaN,$3.00,-$1.50,$1.50,$0.00,I3xT8ioEf4bJar4hJKqNj1geV,NwTbmy7A4WKHPxQ0Nl7qltYZuaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,NaN,XVVXTW4PG7B7T5IVEYUYXDKS,Visa,4506.0
496,2022-05-06,15:36:04,Central Time (US & Canada),NaN,Hot chocolate,1.0,Regular,NaN,NaN,$3.00,-$1.50,$1.50,$0.00,4d0FM3N8YrUzdqiZ5o4zuwgeV,HdtYiVWGQOtvOiizsgNo5pmFvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,N2TT7M952H3X96JW5YPABWDC1W,Aadam Suleman,NaN,ea,1,Physical Good,NaN,NaN,GE72AM5YDMRXKILM7HLJSSRC,Visa,917.0
497,2022-05-06,14:57:42,Central Time (US & Canada),Extras,Oat milk,1.0,Regular,NaN,NaN,$0.75,-$0.37,$0.38,$0.00,WiXDRvduIFEKyehpBUnnNZmeV,vLgjIqMl7zbh7bUkIZOo1vItvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,NaN,N5OGPGI7STZWO5CGVNY32LE2,Visa,4088.0
498,2022-05-06,14:57:42,Central Time (US & Canada),Extras,Vanilla Flavor,1.0,Regular,NaN,NaN,$0.50,-$0.25,$0.25,$0.00,WiXDRvduIFEKyehpBUnnNZmeV,vLgjIqMl7zbh7bUkIZOo1vItvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,NaN,22E0EDAF-DDED-43B2-83E6-28634DAC6304,Visa,4088.0
499,2022-05-06,14:57:42,Central Time (US & Canada),Espresso Drinks,Latte,1.0,Regular,NaN,NaN,$4.00,-$2.00,$2.00,$0.00,WiXDRvduIFEKyehpBUnnNZmeV,vLgjIqMl7zbh7bUkIZOo1vItvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,NaN,VWPCBBUZB7VCAFGTJWK4GKWN,Visa,4088.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49690,2025-08-26,10:32:09,Central Time (US & Canada),Teas,Matcha Latte,1.0,Regular,NaN,"To go, Iced, Oat, Lavender, Regular",$6.75,-$6.75,$0.00,$0.00,SkCHNzWRpCdhk7RTTbCVEimeV,bnDRXepcHhGzaKFPxM439Gl7vaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,MWGA4DJR7A2O6CONTZDV4CUM,NaN,NaN
49726,2025-08-25,13:35:46,Central Time (US & Canada),Espresso Drinks,Cappuccino,1.0,Regular,NaN,"Regular, To go, Whole",$4.25,-$4.25,$0.00,$0.00,0lbBXNxDWEuBvOqos2EYjShnjzIZY,Df3IWA6yyd8s9rS4yCXJ5pvfq0KZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,ZEVMUUXK3J3HJ62R53FYRMDN,Visa,2877
49760,2025-08-25,11:12:01,Central Time (US & Canada),Espresso Drinks,Latte,1.0,Regular,NaN,"Regular, To go, Iced, Whole, Vanilla",$5.00,-$5.00,$0.00,$0.00,of1ODxM6FM8kuk9KIt90hW9QVuMZY,JcomudsfdmaYrelr8QyxTZR38WcZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,VWPCBBUZB7VCAFGTJWK4GKWN,NaN,NaN
49791,2025-08-25,09:38:00,Central Time (US & Canada),Teas,Matcha Latte,1.0,Regular,NaN,"To go, Iced, Almond, Vanilla, Regular",$6.50,-$6.50,$0.00,$0.00,YJySOSux0VbsfeAqzOT1fCKci8PZY,r1MUvi9Fwer2nOvrcBPHkUbKO8TZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,MWGA4DJR7A2O6CONTZDV4CUM,Visa,9205
49792,2025-08-25,09:35:26,Central Time (US & Canada),Teas,Matcha Latte,1.0,Regular,NaN,"To go, Iced, Whole, Vanilla, Regular",$5.75,-$5.75,$0.00,$0.00,6OggYcCZNcXcCm3cXDXCuP9Du5RZY,54gp2bmhvWi8FNzSBFMzKnfRDiVZY,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,MWGA4DJR7A2O6CONTZDV4CUM,NaN,NaN

In [865]:
sales['Count'].unique() # array([ 1,  3,  2, 10, -1,  8,  5,  4,  7])
sales[sales['Count'] != 1] # I think count and qty are the same thing

sales[sales['Count'] != sales['Qty']] # confirms it, ill take Count over qty since qty is a float

Empty DataFrame
Columns: [Date, Time, Time Zone, Category, Item, Qty, Price Point Name, SKU, Modifiers Applied, Gross Sales, Discounts, Net Sales, Tax, Transaction ID, Payment ID, Device Name, Notes, Details, Event Type, Location, Dining Option, Customer ID, Customer Name, Customer Reference ID, Unit, Count, Itemization Type, Fulfillment Note, Channel, Token, Card Brand, PAN Suffix]
Index: []

In [866]:
sales['PAN Suffix'].notna().sum() # 46753 
len(sales['PAN Suffix']) # 49777 obs
print(46753/49777) # There are 93.92% of the data remaining this is a useful identifier for customer with the only downside being customers using differnt cards but the other identfiers like the Ids don't have enough data in them

0.9392490507664182

In [867]:
sales_clean = sales.drop(columns=['Time Zone', 'Price Point Name','Tax', 'Customer ID',
                             'Qty',  'Payment ID', 'SKU', 
                            'Customer Name', 'Customer Reference ID', 'Device Name',
                              'Unit', 'Details', 'Event Type',
                              'Channel', 'Location', 'Fulfillment Note', 'Dining Option', 
                              'Itemization Type', 'Card Brand'])
""" 
Got rid of:
Time Zone - Always going to be the same and unhelpful
'Price Point Name' - Generally unhelpful and random information (Also getting rid of anything with Price point = NAN since those have unspecified drinks and skew the data )
Tax - always 0 since we're non-profit
Customer ID - has over 50% missing data so its an unhelpful identifer
Qty - duplicate of Count except its a float
Transaction ID- theres a unqiue TID for every transaction so unhelpful idenfiter and I can't think of a use for this for now (EDIT: FOUND A USE FOR IT CAN BE USED FOR TRANSACTIONS WITH MULTIPLE DRINKS SINCE EACH DRINK FALLS ON SEPERATE ROW !!!)
Customer Name - like realistically I'm not going to need this unless I want to do like a look up feature
Customer Reference ID- barley any useable data
Payment ID- Same issue as Transaction ID
SKU- all NaN
Device name - always going to be Ipad
Unit- every Row is Ea
Details- just a URL
Event Type - Always Payment and unhelpful
Channel - almost every row was Cor Coffee so unhelpful
Location- always Cor
Fulfillment Note - Full of NAs
Dining Option - Not Applicable
Itemization Type - All Physical good nothing useful
Card Brand - no use


Keeping:
'Date'- need this as an identifer for days
'Time' -  need this as an identifer for time
'Category' - can classify espresso vs teas like matcha, chai, LF
'Item',  - gives exact drink
'Modifiers Applied', - gives the milk, temp, syrups
'Gross Sales', -sales before discount
 'Discounts',  -discount
 'Net Sales',  - sale after discount
 'Notes',  - gives notes such as tea types, 
 'Count', -gives number of drinks bought per order
 'Token', -retruns items that are spelled similarly to each other
'PAN Suffix' -- last four digits of someones card can be used as an identifer

"""



sales_clean.head()

,Date,Time,Category,Item,Modifiers Applied,Gross Sales,Discounts,Net Sales,Transaction ID,Notes,Count,Token,PAN Suffix
0,2020-05-09,11:10:24,Drinks,Latte,NaN,$3.00,$0.00,$3.00,orJGaJC50EssZL75PdNmI49eV,NaN,1,VWPCBBUZB7VCAFGTJWK4GKWN,6073.0
1,2020-05-09,11:09:45,Drinks,Latte,NaN,$3.00,$0.00,$3.00,iSyafDYub6ZtNv9htZNhKrpeV,NaN,1,VWPCBBUZB7VCAFGTJWK4GKWN,NaN
2,2020-03-11,14:55:19,Drinks,Coffee,NaN,$2.00,$0.00,$2.00,ELE9rssYcA12gouEXOA2us4eV,12 oz Drip Coffee,1,5H2VGAOSSRFG3N3AZA4CGBAB,5240.0
3,2020-03-11,12:52:54,Drinks,Coffee,NaN,$2.00,$0.00,$2.00,UrgTE9EiIM0Zcklh4zWCmz6eV,12 oz Drip Coffee,1,5H2VGAOSSRFG3N3AZA4CGBAB,5879.0
4,2020-03-10,15:26:46,Drinks,Tea,NaN,$3.00,$0.00,$3.00,EjQr2w7zLb2CxBFpuPaLqs4eV,NaN,1,D78EA7BB-B863-43AC-B95F-0D4DD2E6C8C4,9179.0

In [868]:
sales_clean.columns

Index(['Date', 'Time', 'Category', 'Item', 'Modifiers Applied', 'Gross Sales',
       'Discounts', 'Net Sales', 'Transaction ID', 'Notes', 'Count', 'Token',
       'PAN Suffix'],
      dtype='str')

In [869]:
sales_clean.info() 
"""
 Need to convert: Date into date, 
 Time into time,
GS into double,
Discounts into double
Net into double

Maybe turn Item, catagory, Token as factors or whatever is Pandas equivalant?

"""

<class 'pandas.DataFrame'>
Index: 49777 entries, 0 to 49801
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               49777 non-null  str
 1   Time               49777 non-null  str
 2   Category           49136 non-null  str
 3   Item               49777 non-null  str
 4   Modifiers Applied  41758 non-null  object
 5   Gross Sales        49777 non-null  str
 6   Discounts          49777 non-null  str
 7   Net Sales          49777 non-null  str
 8   Transaction ID     49777 non-null  str
 9   Notes              5811 non-null   str
 10  Count              49777 non-null  int64
 11  Token              49777 non-null  str
 12  PAN Suffix         46753 non-null  object
dtypes: int64(1), object(2), str(10)
memory usage: 10.4+ MB

'\n Need to convert: Date into date, \n Time into time,\nGS into double,\nDiscounts into double\nNet into double\n\nMaybe turn Item, catagory, Token as factors or whatever is Pandas equivalant?\n\n'

In [870]:
# Takes care of every neccesary Conversion
sales_clean['Date'] = pd.to_datetime(sales_clean['Date'])
sales_clean['Time'] = pd.to_datetime(sales_clean['Time'], format='%H:%M:%S').dt.time

for col in ['Gross Sales', 'Discounts', 'Net Sales']:
    sales_clean[col] = sales_clean[col].replace(r'[\$,]', '', regex=True).astype(float)

sales_clean['Category'] = sales_clean['Category'].astype('category')
sales_clean['Item'] = sales_clean['Item'].astype('category')

-- Plots Needed
There will be a calender where you can select days so all these will change

number of Sales number
Profit number?

Cumulative sales 
milks ranked (table)
Syrup ranked (table)

number of iced and number of hot
Most item sold

Most frequent comobo

Weather

In [871]:
TotalSales = sales_clean['Count'].sum()
TotalProfit = sales_clean['Net Sales'].sum()

#sales_clean['Temp'] = np.where(sales_clean['Modifiers Applied'].str.contains("hot", case=False, na=False), "Hot", "Iced")
sales_clean.head() # Theres an issue where drinks in 2020 are unspecifieced I think I will get rid of these because 
len(sales2019) # 479 values
sales2019.tail(100) 
# Looks like they are specified I only assumed they were unspecified since the first couple were just Lattes but the issue is that there is no modifers applied for these
# A work around that I can do is that I know some drink like Capp are always hot so i have to make sure that those are hot

"""
len(sales_clean[(sales_clean['Temp'] == 'Iced') & (sales_clean['Item'].str.contains("Cap"))]) # 2078 values with cold capp
((sales_clean['Item'].str.contains("Cap"))).sum() # out of 2109 total Cap orders this is intreasting since i would assume baristas wouldn't select a temp option for capp
len(sales_clean[(sales_clean['Temp'] == 'Hot') & (sales_clean['Item'].str.contains("Cap"))]) # 31 values with Hot capp okay so math adds up

# It looks like Ill have to manually select some drinks as hot or iced
sales['Item'].unique()

[                   'Latte',                   'Coffee',
                      'Tea',                'Capuccino',
                'Americano',              'Almond Milk',
           'Vanilla Flavor',                 'Espresso',
                 'Oat milk',           'Iced Americano',***
            'Hot chocolate',           'Lavender Latte',
               'Flat White',               'Chai Latte',
               'Extra shot',                 'Kind Bar',
          'Iced Chai Latte',               'Iced Mocha',***
                   'Lavlem',                  'Steamer',
                    'Mocha',               'Dirty Chai',
               'Iced Latte',***                'Cold Brew',
                'Macchiato',                 'Iced Tea',***
          'Lavender flavor',            '3 cookie deal',
               'Baked good',                  'Sticker',
                'Cafe Miel',            'Mexican Mocha',
        'Mexican Hot Cocoa',                   'Beanie',
                  'Cortado',     'Peppermint Hot Cocoa',
         'Peppermint Mocha',        'Gingerbread Latte',
        'Pumpkin Pie Latte',                   'Cookie',
            '2 cookie deal',            'Iced Espresso',***
                   'Tshirt',                 'Lemonade',
               'Cappuccino', 'Peppermint Hot Chocolate',
             'Matcha Latte',                 'Affogato',
...
          'Matcha lemonade',                      'Cap',
          'Breve Special 😘',                     'Soda',
                  'Flowers',            'Breve Special',
     'Summit S'mores Latte']

     
""" 

# On Second thought instead of searching for hot in the modifers and doing iced if its not found ill have it the other way since most drinks are hot and they won't have a modfier that says otherwise
sales_clean['Temp'] = np.where(sales_clean['Modifiers Applied'].str.contains("iced", case=False, na=False), "Iced", "Hot")
len(sales_clean[(sales_clean['Temp'] == 'Hot') & (sales_clean['Item'].str.contains("Cap"))]) # This is now 2109 which matches the number of capp orders
# Looking at the unique number of items theres a lot of iced stuff that ill have to hard encode: 'Iced Latte', 'Iced Americano', 'Iced Mocha', 'Iced Tea', 'Iced Espresso'
# I want to get rid of these catagories and consolidate them

sales_clean.loc[sales_clean["Item"] == 'Iced Latte', "Temp"] = "Iced"
sales_clean.loc[sales_clean["Item"] == 'Iced Latte', "Item"] = "Latte"

sales_clean.loc[sales_clean["Item"] == 'Iced Americano', "Temp"] = "Iced"
sales_clean.loc[sales_clean["Item"] == 'Iced Americano', "Item"] = "Americano"

sales_clean.loc[sales_clean["Item"] == 'Iced Mocha', "Temp"] = "Iced"
sales_clean.loc[sales_clean["Item"] == 'Iced Mocha', "Item"] = "Mocha"

sales_clean.loc[sales_clean["Item"] == 'Iced Tea', "Temp"] = "Iced"
sales_clean.loc[sales_clean["Item"] == 'Iced Tea', "Item"] = "Tea"

sales_clean.loc[sales_clean["Item"] == 'Iced Espresso', "Temp"] = "Iced"
sales_clean.loc[sales_clean["Item"] == 'Iced Espresso', "Item"] = "Espresso"


sales_clean.loc[sales_clean["Item"] == 'Iced Chai Latte', "Temp"] = "Iced"
sales_clean.loc[sales_clean["Item"] == 'Iced Chai Latte', "Item"] = "Chai Latte"

print(sales_clean.iloc[567])  # Fixed this row YIPEE

Date                       2022-05-04 00:00:00
Time                                  12:46:47
Category                       Espresso Drinks
Item                                     Latte
Modifiers Applied                          NaN
Gross Sales                                4.0
Discounts                                 -2.0
Net Sales                                  2.0
Transaction ID       g1AyMVENQFJeaGRS83suXbreV
Notes                                      NaN
Count                                        1
Token                 HUIR7LYJXAVJRIUYF3ZYZ6YX
PAN Suffix                              9928.0
Temp                                      Iced
Name: 568, dtype: object

In [872]:
sales_clean.groupby('Category')['Item'].unique() # catagories not very helpful but ill keep it around for now

Category
Coffee Drinks      ['Coffee', 'Cold Brew', 'Cafe Miel', 'Gingerbr...
Drinks             ['Latte', 'Coffee', 'Tea', 'Capuccino', 'Ameri...
Espresso Drinks    ['Americano', 'Latte', 'Lavender Latte', 'Flat...
Extras             ['Oat milk', 'Vanilla Flavor', 'Extra shot', '...
Food               ['Kind Bar', '3 cookie deal', 'Baked good', 'C...
Merch              ['Sticker', 'Beanie', 'Catholic Flames Shirt',...
Other Drinks       ['Lemonade', 'Hot chocolate', 'Steamer', 'Hot ...
Teas               ['Chai Latte', 'Tea', 'Matcha Latte', 'London ...
Name: Item, dtype: object

In [873]:
# Another issue in this data set is the breve special with the emoji being its own seperate thing
"""
[                   'Latte',                   'Coffee',
                      'Tea',                'Capuccino',
                'Americano',              'Almond Milk',
           'Vanilla Flavor',                 'Espresso',
                 'Oat milk',           'Iced Americano',***
            'Hot chocolate',           'Lavender Latte',
               'Flat White',               'Chai Latte',
               'Extra shot',                 'Kind Bar',
          'Iced Chai Latte',               'Iced Mocha',***
                   'Lavlem',                  'Steamer',
                    'Mocha',               'Dirty Chai',
               'Iced Latte',***                'Cold Brew',
                'Macchiato',                 'Iced Tea',***
          'Lavender flavor',            '3 cookie deal',
               'Baked good',                  'Sticker',
                'Cafe Miel',            'Mexican Mocha',
        'Mexican Hot Cocoa',                   'Beanie',
                  'Cortado',     'Peppermint Hot Cocoa',
         'Peppermint Mocha',        'Gingerbread Latte',
        'Pumpkin Pie Latte',                   'Cookie',
            '2 cookie deal',            'Iced Espresso',***
                   'Tshirt',                 'Lemonade',
               'Cappuccino', 'Peppermint Hot Chocolate',
             'Matcha Latte',                 'Affogato',
...
          'Matcha lemonade',                      'Cap',
          'Breve Special 😘',                     'Soda',
                  'Flowers',            'Breve Special',
     'Summit S'mores Latte']

"""
sales_clean[sales_clean["Item"] == 'Breve Special 😘'] # I will consolidate these with the other breve special

sales_clean.loc[sales_clean["Item"] == 'Breve Special 😘', "Item"] = 'Breve Special'

In [874]:
sales_clean[sales_clean['Item'] == 'Breve Special 😘'] # theres no rows YIPE

Empty DataFrame
Columns: [Date, Time, Category, Item, Modifiers Applied, Gross Sales, Discounts, Net Sales, Transaction ID, Notes, Count, Token, PAN Suffix, Temp]
Index: []

In [875]:
sales_clean['Item'] = sales_clean['Item'].cat.remove_unused_categories()
#for i in sales_clean['Item'].unique():
#    print(i)

"""
Whelp i actually missed a lot whoops

Latte
Coffee
Tea
Capuccino
Americano
Almond Milk
Vanilla Flavor
Espresso
Oat milk
Iced Americano
Hot chocolate
Lavender Latte
Flat White
Chai Latte
Extra shot
Kind Bar
Iced Chai Latte
Iced Mocha
Lavlem
Steamer
Mocha
Dirty Chai
Cold Brew
Macchiato
Iced Tea
Lavender flavor
3 cookie deal
Baked good
Sticker
Cafe Miel
Mexican Mocha
Mexican Hot Cocoa
Beanie
Cortado
Peppermint Hot Cocoa
Peppermint Mocha
Gingerbread Latte
Pumpkin Pie Latte
Cookie
2 cookie deal
Iced Espresso
Tshirt
Lemonade
Cappuccino
Peppermint Hot Chocolate
Matcha Latte
Affogato
Cafe Au Lait
Hot Chocolate
LiaP Cookie
Taos Bar
Affagado
London Fog
Red Eye
Catholic Flames Shirt
T-shirt
Pullover
Travel Mug
Taos Granola Bar
Hot Chocolate 
Tote bag
Pullover Sweater
Hot Cocoa
Matcha lemonade
Cap
Breve Special
Soda
Flowers
Summit S'mores Latte

"""

#What tf is vanilla flavor?
sales_clean[sales_clean['Item'] == "Vanilla Flavor"] # looks like syrup sold as an item, lets check the item after index 32
sales_clean.iloc[32] # Item VF Date: 3-3-2020 time: 14:17:34

sales_clean.iloc[33] # item latte date 3-3-2020 time 14:17:34
# based off this i can conclude that that the nth index is flavor and n+1 is the drink up until

Date                       2020-03-03 00:00:00
Time                                  14:17:34
Category                                Drinks
Item                                     Latte
Modifiers Applied                          NaN
Gross Sales                                3.0
Discounts                                  0.0
Net Sales                                  3.0
Transaction ID       oP7qk5Efz5WzaeVfhp5kQPkeV
Notes                                      NaN
Count                                        1
Token                 VWPCBBUZB7VCAFGTJWK4GKWN
PAN Suffix                              7562.0
Temp                                       Hot
Name: 33, dtype: object

In [876]:
sales_clean[sales_clean["Item"].str.contains("flavor", case=False)] # 588 rows???? are we so serious
sales_clean[sales_clean["Item"].str.contains("flavor", case=False)]['Item'].unique() # There only two flavors like this vanilla and Lavender

['Vanilla Flavor', 'Lavender flavor']
Categories (64, str): ['2 cookie deal', '3 cookie deal', 'Affagado', 'Affogato', ..., 'Tote bag', 'Travel Mug', 'Tshirt', 'Vanilla Flavor']

In [892]:
# Lets test out my theory. if n and n + 1 have the same (or extremly close) time of sale, then I can consider them to be the same order where n is rows with item = Flavor and n + 1 are rows with item = the syrup the flavor belongs to
sales_clean = sales_clean.reset_index(drop=True)
flavorRows = sales_clean[sales_clean["Item"].str.contains("flavor", case=False)].index # create a list of indexes with rows of flavor aka n
#print(flavorRows) #sanity check, this has 588 rows
flavorSyrupRows = flavorRows + 1 # this is indexes of hypthetical drinks without flavor
#print(flavorSyrupRows) #  check



from datetime import datetime, date

paired_with = {}  # i -> the index of its paired drink row

for i in flavorRows:
    has_next = (i + 1) in sales_clean.index
    has_prev = (i - 1) in sales_clean.index and i - 1 >= 0

    diff_next = None
    diff_prev = None

    if has_next:
        t_i = datetime.combine(date.today(), sales_clean.loc[i, 'Time'])
        t_next = datetime.combine(date.today(), sales_clean.loc[i + 1, 'Time'])
        diff_next = abs((t_next - t_i).total_seconds())

    if has_prev:
        t_prev = datetime.combine(date.today(), sales_clean.loc[i - 1, 'Time'])
        t_i = datetime.combine(date.today(), sales_clean.loc[i, 'Time'])
        diff_prev = abs((t_i - t_prev).total_seconds())

    # decide which neighbor (if any) is the actual pair
    candidates = []
    if diff_next is not None and diff_next < 2:
        candidates.append((diff_next, i + 1))
    if diff_prev is not None and diff_prev < 2:
        candidates.append((diff_prev, i - 1))

    if candidates:
        candidates.sort()               # smallest gap first
        paired_with[i] = candidates[0][1]  # take the closer one

print(len(paired_with))

#print(len(matchesNext) + len(matchesPrev)) # 587 THATS ALMOST ALL OF THEM

# trying to find the other one
matched_indices = set()
for i in flavorRows:
    has_next = (i + 1) in sales_clean.index
    has_prev = (i - 1) in sales_clean.index and i - 1 >= 0
    matched = False
    if has_next:
        t_i = datetime.combine(date.today(), sales_clean.loc[i, 'Time'])
        t_next = datetime.combine(date.today(), sales_clean.loc[i + 1, 'Time'])
        if abs((t_next - t_i).total_seconds()) < 2:
            matched = True
    if has_prev:
        t_prev = datetime.combine(date.today(), sales_clean.loc[i - 1, 'Time'])
        t_i = datetime.combine(date.today(), sales_clean.loc[i, 'Time'])
        if abs((t_i - t_prev).total_seconds()) < 2:
            matched = True
    if matched:
        matched_indices.add(i)

unmatched = flavorRows.difference(matched_indices)
sales_clean.loc[unmatched]

sales_clean.loc[unmatched+1]  # should be either 9:07:08 if i-1 OR 9:09:28 if i + 1: result its i - 1 70 second difference thats a huge gap tho so i think its better to remove this row

sales_clean.drop(index=unmatched, inplace=True) # drop bad row

# Okay now that my theory has been proven, lets combine the drinks with their syrups

flavor = ""
for key, value in paired_with.items(): # This changes all those drinks to have the flavorings and updates its sales info as well
    flavor = sales_clean.loc[key, "Item"][:-7]
    gSales = sales_clean.loc[key, "Gross Sales"] + sales_clean.loc[value, "Gross Sales"]
    discount = sales_clean.loc[key, "Discounts"] + sales_clean.loc[value, "Discounts"] 
    nSales = sales_clean.loc[key, "Net Sales"] + sales_clean.loc[value, "Net Sales"]

    sales_clean.loc[value, "Modifiers Applied"] = sales_clean.loc[value, "Modifiers Applied"].fillna('') + ", " + flavor
    sales_clean.loc[value, "Gross Sales"] = gSales
    sales_clean.loc[value, "Discounts"] = discount
    sales_clean.loc[value, "Net Sales"] = nSales

    #print(sales_clean.iloc[32]) # this is an error so everything is good!!
sales_clean.drop(index = paired_with.keys(), inplace = True)

0

In [ ]:
for i in sales_clean['Item'].unique():
    print(i)

"""
Changes to make:
Count > 1?  **************************RESOLVED
check to see if dirty chai is run up as chai latte w extra shot of esp *******************DONE
extra shot                          *******************DONE
baked good ??                              *******************DONE
Hot Chocolate                                 *******************DONE
Affogato vs afagado                             *******************DONE
LiAp cookie vs 1 cookie vs 2 cookie vs 3 cookie   *******************DONE


Count vanilla and hot for LF                *******************DONE
Counting chocolate ganache for mocha and HC *******************DONE
count breve for half and half               *******************DONE

Cappuccino vs Capuccino                     *******************DONE
Taos bar vs Taos Granola bar                *******************DONE

Almond milk?                                ********************DONE
Oat milk                                        ***************DONE
Lavender latte                                 ****************DONE
Lavlem                                          ****************DONE
cafe miel                                      *******************DONE
pepperment hot cocoa                           ****************DONE
pepermint mocha                                 ****************DONE
gingerbread Latte                                ****************DONE
Pumpkin pie Latte                               ****************DONE
peppermint HOt chocolate                         ****************DONE
Summit S'mores Latte                            ****************DONE

Cafe vs decaf                         *******************************DONE  


consider getting rid of:
mexican mocha (just mocha)                  *******************************DONE            
mexican Hot Cocoa (just HC)                 *******************************DONE

FIX CATAGORIES                              *************************DONE

--Need to make:
milk type               *******************************DONE
to go or for here       *******************************DONE
syrup                   *******************************DONE          
sweet or regular (for matcha) *************************DONE



-- Plots Needed
There will be a calender where you can select days so all these will change

number of Sales number
Profit number?

Cumulative sales 
milks ranked (table)
Syrup ranked (table)

number of iced and number of hot
Most item sold

Most frequent comobo

Weather

"""
#sales_clean.tail(500)

Latte
Coffee
Tea
Capuccino
Americano
Almond Milk
Espresso
Oat milk
Hot chocolate
Lavender Latte
Flat White
Chai Latte
Extra shot
Kind Bar
Mocha
Lavlem
Steamer
Dirty Chai
Cold Brew
Macchiato
3 cookie deal
Baked good
Sticker
Cafe Miel
Mexican Mocha
Mexican Hot Cocoa
Beanie
Cortado
Peppermint Hot Cocoa
Peppermint Mocha
Gingerbread Latte
Pumpkin Pie Latte
Cookie
2 cookie deal
Tshirt
Lemonade
Cappuccino
Peppermint Hot Chocolate
Matcha Latte
Affogato
Cafe Au Lait
Hot Chocolate
LiaP Cookie
Taos Bar
Affagado
London Fog
Red Eye
Catholic Flames Shirt
T-shirt
Pullover
Travel Mug
Taos Granola Bar
Hot Chocolate
Tote bag
Pullover Sweater
Hot Cocoa
Matcha lemonade
Cap
Breve Special
Soda
Flowers
Summit S'mores Latte

"\nChanges to make:\nCount > 1?  **************************RESOLVED\ncheck to see if dirty chai is run up as chai latte w extra shot of esp *******************DONE\nextra shot                          *******************DONE\nbaked good ??                              *******************DONE\nHot Chocolate                                 *******************DONE\nAffogato vs afagado                             *******************DONE\nLiAp cookie vs 1 cookie vs 2 cookie vs 3 cookie   *******************DONE\n\n\nCount vanilla and hot for LF                *******************DONE\nCounting chocolate ganache for mocha and HC *******************DONE\ncount breve for half and half               *******************DONE\n\nCappuccino vs Capuccino                     *******************DONE\nTaos bar vs Taos Granola bar                *******************DONE\n\nAlmond milk?                                ********************DONE\nOat milk                                        ***************DONE\nLavender latte                                 ****************DONE\nLavlem                                          ****************DONE\ncafe miel                                      *******************DONE\npepperment hot cocoa                           ****************DONE\npepermint mocha                                 ****************DONE\ngingerbread Latte                                ****************DONE\nPumpkin pie Latte                               ****************DONE\npeppermint HOt chocolate                         ****************DONE\nSummit S'mores Latte                            ****************DONE\n\nCafe vs decaf                         *******************************DONE  \n\n\nconsider getting rid of:\nmexican mocha (just mocha)                  *******************************DONE            \nmexican Hot Cocoa (just HC)                 *******************************DONE\n\nFIX CATAGORIES\n\n--Need to make:\nmilk type               *******************************DONE\nto go or for here       *******************************DONE\nsyrup                   *******************************DONE          \nsweet or regular (for matcha) *************************DONE\n\n\n\n-- Plots Needed\nThere will be a calender where you can select days so all these will change\n\nnumber of Sales number\nProfit number?\n\nCumulative sales \nmilks ranked (table)\nSyrup ranked (table)\n\nnumber of iced and number of hot\nMost item sold\n\nMost frequent comobo\n\nWeather\n\n"

In [879]:
sales_clean.loc[sales_clean["Item"] == "Taos Granola Bar", "Item"] = "Taos Bar"
sales_clean.loc[sales_clean["Item"] == "Mexican Mocha", "Item"] = "Mocha"
sales_clean.loc[sales_clean["Item"] == "Mexican Hot Cocoa", "Item"] = "Hot Chocolate"
len(sales_clean[sales_clean['Item'] == 'Baked good']) # Im going to get rid of baked good since we never really use it again and theres only 32 points of data and it was sold for a dollar
sales_clean.drop(index=sales_clean[sales_clean['Item'] == 'Baked good'].index, inplace = True)
sales_clean.loc[(sales_clean["Item"] == "Chai Latte") & (sales_clean["Modifiers Applied"].str.contains("Shot", case = False, na=False)), "Item"] = "Dirty Chai"

In [880]:
# Need to check if count is for one drink counted twice or can be multiple different drinks
sales_clean[sales_clean['Count'] > 1].tail()
print(sales_clean.loc[49027])
print(sales_clean.loc[49028])
 # These have the same exact time stamp so i think when count is 2 the order after is apart of that order but in the second order the total isn't reflected like. Maybe it will have the same transactionID?

print(sales.loc[49027])
print(sales.loc[49028]) # since ive been dropping rows the rows of sales (original) and sales_clean (new) are no longer the same :( Ill have to use date and Time as the way to do ts

sales[(sales['Date'] == '2025-08-26') & (sales['Time'] == '13:37:09')] # TRANSACTION ID IS THE SAME LETS GOOOO

# wait does that mean theres an easier way to find syrup flavors and its corresponding drinks??
#print(sales.loc[32])
#print(sales.loc[33]) # yeah looks it was a lot easier to find syrup flavor and its corresponding using transaction ID but theres really no need to go back and fix it 
# My theory about count was wrong it measures the quantity of the same exact item (down to modifers) and i can use transaction ID to find exact orders so I will bring this back

Date                           2025-09-04 00:00:00
Time                                      11:59:30
Category                           Espresso Drinks
Item                                      Espresso
Modifiers Applied                   Regular, To go
Gross Sales                                   3.25
Discounts                                      0.0
Net Sales                                     3.25
Transaction ID       WOnRLxq7ptlCG6IYVFp3tH8awZQZY
Notes                                          NaN
Count                                            1
Token                     Q5DEHJG25BF4T6FBAGBC2QTK
PAN Suffix                                    6497
Temp                                           Hot
Name: 49027, dtype: object
Date                               2025-09-04 00:00:00
Time                                          11:58:33
Category                               Espresso Drinks
Item                                             Latte
Modifiers Applied    Regular, To go, Iced, Whole, Rose
Gross Sales                                       5.25
Discounts                                          0.0
Net Sales                                         5.25
Transaction ID           I5YFvbkVFj2HNEk0abfMkpiX9bdZY
Notes                                              NaN
Count                                                1
Token                         VWPCBBUZB7VCAFGTJWK4GKWN
PAN Suffix                                        1495
Temp                                              Iced
Name: 49028, dtype: object
Date                                                            2025-09-04
Time                                                              13:37:32
Time Zone                                       Central Time (US & Canada)
Category                                                   Espresso Drinks
Item                                                            Cappuccino
Qty                                                                    1.0
Price Point Name                                                   Regular
SKU                                                                    NaN
Modifiers Applied                                    Regular, To go, Whole
Gross Sales                                                          $4.25
Discounts                                                            $0.00
Net Sales                                                            $4.25
Tax                                                                  $0.00
Transaction ID                               SaOT2O6AznSGUj4tqhskKOnlqxEZY
Payment ID                                   JcYiqqK8KIml2uCtX4cfAHfK1qHZY
Device Name                                                           iPad
Notes                                                                  NaN
Details                  https://app.squareup.com/dashboard/sales/trans...
Event Type                                                         Payment
Location                                                        Cor Coffee
Dining Option                                                          NaN
Customer ID                                                            NaN
Customer Name                                                          NaN
Customer Reference ID                                                  NaN
Unit                                                                    ea
Count                                                                    1
Itemization Type                                             Physical Good
Fulfillment Note                                                       NaN
Channel                                                         Cor Coffee
Token                                             ZEVMUUXK3J3HJ62R53FYRMDN
Card Brand                                                            Visa
PAN Suffix                                                            9031
Name: 49027, dtype: object
Date                                                            2025-09-04
Time                                                              13:36:59
Time Zone                                       Central Time (US & Canada)
Category                                                              Teas
Item                                                          Matcha Latte
Qty                                                                    1.0
Price Point Name                                                   Regular
SKU                                                                    NaN
Modifiers Applied                    To go, Iced, Whole, Lavender, Regular
Gross Sales                                                          $6.00
Discounts                                                            $0.00
Net Sales                                                            $6.00
Tax                                                                  $0.00
Transaction ID                               C6M4gJ3AlRofOkWG8B5zu2VgLucZY
Payment ID                                   FsJQFrhDrLhvCArUnZBCdIafOmUZY
Device Name                                                           iPad
Notes                                                                  NaN
Details                  https://app.squareup.com/dashboard/sales/trans...
Event Type                                                         Payment
Location                                                        Cor Coffee
Dining Option                                                          NaN
Customer ID                                     AY5VK9FMSRY5G9Y2TVPAEC36QC
Customer Name                                                          NaN
Customer Reference ID                                                  NaN
Unit                                                                    ea
Count                                                                    1
Itemization Type                                             Physical Good
Fulfillment Note                                                       NaN
Channel                                                         Cor Coffee
Token                                             MWGA4DJR7A2O6CONTZDV4CUM
Card Brand                                                            Visa
PAN Suffix                                                            2014
Name: 49028, dtype: object

,Date,Time,Time Zone,Category,Item,Qty,Price Point Name,SKU,Modifiers Applied,Gross Sales,Discounts,Net Sales,Tax,Transaction ID,Payment ID,Device Name,Notes,Details,Event Type,Location,Dining Option,Customer ID,Customer Name,Customer Reference ID,Unit,Count,Itemization Type,Fulfillment Note,Channel,Token,Card Brand,PAN Suffix
49640,2025-08-26,13:37:09,Central Time (US & Canada),Espresso Drinks,Latte,2.0,Regular,NaN,"Regular, To go, Hot, Whole, Vanilla",$10.00,$0.00,$10.00,$0.00,c92e4QLMPKZxH5gO0peikLheV,tW4upc2dDUWVKfysZtske5WMvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,2,Physical Good,NaN,Cor Coffee,VWPCBBUZB7VCAFGTJWK4GKWN,Visa,0397
49641,2025-08-26,13:37:09,Central Time (US & Canada),Other Drinks,Hot Chocolate,1.0,Regular,NaN,"To go, Whole",$3.75,$0.00,$3.75,$0.00,c92e4QLMPKZxH5gO0peikLheV,tW4upc2dDUWVKfysZtske5WMvaB,iPad,NaN,https://app.squareup.com/dashboard/sales/trans...,Payment,Cor Coffee,NaN,NaN,NaN,NaN,ea,1,Physical Good,NaN,Cor Coffee,GE72AM5YDMRXKILM7HLJSSRC,Visa,0397

In [881]:

sales.groupby('Transaction ID').size().value_counts()

1     37329
2      5080
3       585
4        84
5        22
6         7
9         2
8         1
7         1
12        1
Name: count, dtype: int64

In [882]:
""" 
Lavlem                  #####
cafe miel               ####
pepperment hot cocoa    ####
pepermint mocha         ####
gingerbread Latte       #####
Pumpkin pie Latte       #####
peppermint HOt chocolate #####
Summit S'mores Latte     ######
"""

# Fixing Lavender latte to just be latte w lavender

# len(sales_clean.loc[sales_clean['Item'] == "Lavender Latte", "Modifiers Applied"]) # 52 LL
#sales_clean.loc[sales_clean['Item'] == "Lavender Latte", "Modifiers Applied"].isna().sum() # 52 NAs so instead of appending i can just replace modifers applied
sales_clean.loc[sales_clean['Item'] == "Lavender Latte", "Modifiers Applied"] = "Lavender"
sales_clean.loc[sales_clean['Item'] == "Lavender Latte"] 
sales_clean.loc[sales_clean['Item'] == "Lavender Latte", "Item"] = "Latte" 

# Fixing Lavlem to be Lemonade w lavender

sales_clean.loc[sales_clean['Item'] == "Lavlem", "Modifiers Applied"] = "Lavender"
sales_clean.loc[sales_clean['Item'] == "Lavlem", "Item"] = "Lemonade"  

# Fixing Cafe Miel to be latte with Cafe Miel

#sales_clean.loc[sales_clean['Item'] == "Cafe Miel", "Modifiers Applied"].isna().sum() # 52 NA
#len(sales_clean.loc[sales_clean['Item'] == "Cafe Miel", "Modifiers Applied"]) # 52 total so i can just replace
sales_clean.loc[sales_clean['Item'] == "Cafe Miel", "Modifiers Applied"] = "Cafe Miel"
sales_clean.loc[sales_clean['Item'] == "Cafe Miel", "Item"] = "Latte"

# Fixing Peppermint hot cocoa to be Hot Chocolate with Peppermind

#sales_clean.loc[sales_clean['Item'] == "Peppermint Hot Cocoa", "Modifiers Applied"].isna().sum() # 18 Nas
#len(sales_clean.loc[sales_clean['Item'] == "Peppermint Hot Cocoa", "Modifiers Applied"]) # 18 total
sales_clean.loc[sales_clean['Item'] == "Peppermint Hot Cocoa", "Modifiers Applied"] = "Peppermint"
sales_clean.loc[sales_clean['Item'] == "Peppermint Hot Cocoa", "Item"] =  "Hot Chocolate"


# Fixing peppermint mocha to be mocha with pepermint

#sales_clean.loc[sales_clean['Item'] == "Peppermint Mocha", "Modifiers Applied"].isna().sum() # 37 Nas
#len(sales_clean.loc[sales_clean['Item'] == "Peppermint Mocha", "Modifiers Applied"]) # 138 need to make sure i don't replace important stuff 
mask = sales_clean['Item'] == "Peppermint Mocha"

mask = sales_clean['Item'] == "Peppermint Mocha"
mods = sales_clean.loc[mask, "Modifiers Applied"]

sales_clean.loc[mask, "Modifiers Applied"] = np.where(
    mods.isna() | mods.str.contains("Peppermint", case=False, na=False),
    mods.fillna("Peppermint"),  # covers the NaN case
    mods + ", Peppermint"        # covers "doesn't have it yet" case
)
sales_clean.loc[sales_clean['Item'] == "Peppermint Mocha", "Item"] =  "Mocha"



# Fixing Gingerbread latte to be latte with Gingerbread
#sales_clean.loc[sales_clean['Item'] == "Gingerbread Latte"] # these have modfiers

mask = sales_clean['Item'] == "Gingerbread Latte"
mods = sales_clean.loc[mask, "Modifiers Applied"]

sales_clean.loc[mask, "Modifiers Applied"] = np.where(
    mods.isna() | mods.str.contains("Gingerbread", case=False, na=False),
    mods.fillna("Gingerbread"),  # covers the NaN case
    mods + ", Gingerbread"        # covers "doesn't have it yet" case
)

sales_clean.loc[sales_clean['Item'] == "Gingerbread Latte", "Item"] = "Latte"


# Fixing Pumpking pie Latte to be Latte with Pumpkin

#sales_clean.loc[sales_clean['Item'] == "Pumpkin Pie Latte"]  same thing with modifiers
mask = sales_clean['Item'] == "Pumpkin Pie Latte"
mods = sales_clean.loc[mask, "Modifiers Applied"]

sales_clean.loc[mask, "Modifiers Applied"] = np.where(
    mods.isna() | mods.str.contains("Pumpkin", case=False, na=False),
    mods.fillna("Pumpkin"),  # covers the NaN case
    mods + ", Pumpkin"        # covers "doesn't have it yet" case
)
sales_clean.loc[sales_clean['Item'] == "Pumpkin Pie Latte", "Item"] = "Latte"


# Fixing Peppermint Hot Chocolate to be Hot chocolate with Peppermint

mask = sales_clean['Item'] == "Peppermint Hot Chocolate"
mods = sales_clean.loc[mask, "Modifiers Applied"]

sales_clean.loc[mask, "Modifiers Applied"] = np.where(
    mods.isna() | mods.str.contains("Peppermint", case=False, na=False),
    mods.fillna("Peppermint"),  # covers the NaN case
    mods + ", Peppermint"        # covers "doesn't have it yet" case
)
sales_clean.loc[sales_clean['Item'] == "Peppermint Hot Chocolate", "Item"] = "Hot Chocolate"

# Fixing SUmmit smores latte to be latte with marshmellow
#sales_clean.loc[sales_clean['Item'] == "Summit S'mores Latte"]  Theres a lot of modifiers 

mask = sales_clean['Item'] == "Summit S'mores Latte"
mods = sales_clean.loc[mask, "Modifiers Applied"]

sales_clean.loc[mask, "Modifiers Applied"] = np.where(
    mods.isna() | mods.str.contains("S'mores", case=False, na=False),
    mods.fillna("S'mores"),  # covers the NaN case
    mods + ", S'mores"        # covers "doesn't have it yet" case
)
sales_clean.loc[sales_clean['Item'] == "Summit S'mores Latte", "Item"] = "Latte"

In [883]:
"""
Lavender latte
Lavlem
cafe miel
pepperment hot cocoa
pepermint mocha
gingerbread Latte
Pumpkin pie Latte
peppermint HOt chocolate
Summit S'mores Latte
"""
#sales_clean[sales_clean['Item'] == 'Almond Milk']

#sales_clean[sales_clean['Transaction ID'] == '81PVQ5yOODaN6ycBqTsZbnzeV'] # Milk type and drink get split into two seperate rows but theyre bound by the same Tranasaction ID

# Fixing Almond milk
for i in sales_clean[sales_clean['Item'] == 'Almond Milk'].index:
    drinkRow = sales_clean[(sales_clean['Transaction ID'] == sales_clean.loc[i, 'Transaction ID']) & (sales_clean.index != i)].index
    sales_clean.loc[drinkRow, 'Modifiers Applied'] = sales_clean.loc[drinkRow, 'Modifiers Applied'] + ", Almond"
    sales_clean.loc[drinkRow, 'Milk'] =  "Almond"
    
    gSale = sales_clean.loc[i, 'Gross Sales']
    discount = sales_clean.loc[i, 'Discounts']
    nSale = sales_clean.loc[i, 'Net Sales']

    sales_clean.loc[drinkRow, 'Gross Sales'] += gSale
    sales_clean.loc[drinkRow, 'Discounts'] += discount
    sales_clean.loc[drinkRow, 'Net Sales'] += nSale

sales_clean = sales_clean.drop(index=sales_clean[sales_clean['Item'] == 'Almond Milk'].index)


# Fixing oat milk
for i in sales_clean[sales_clean['Item'] == 'Oat milk'].index:
    drinkRow = sales_clean[(sales_clean['Transaction ID'] == sales_clean.loc[i, 'Transaction ID']) & (sales_clean.index != i)].index
    sales_clean.loc[drinkRow, 'Modifiers Applied'] = sales_clean.loc[drinkRow, 'Modifiers Applied'] + ", Oat"
    sales_clean.loc[drinkRow, 'Milk'] =  "Oat"
    
    gSale = sales_clean.loc[i, 'Gross Sales']
    discount = sales_clean.loc[i, 'Discounts']
    nSale = sales_clean.loc[i, 'Net Sales']

    sales_clean.loc[drinkRow, 'Gross Sales'] += gSale
    sales_clean.loc[drinkRow, 'Discounts'] += discount
    sales_clean.loc[drinkRow, 'Net Sales'] += nSale

sales_clean = sales_clean.drop(index=sales_clean[sales_clean['Item'] == 'Oat milk'].index)
sales_clean = sales_clean.reset_index(drop=True)  

for i in sales_clean['Item'].unique():
    print(i)

#Fixing Extra shot

for i in sales_clean[sales_clean['Item'] == 'Extra shot'].index:
    drinkRow = sales_clean[(sales_clean['Transaction ID'] == sales_clean.loc[i, 'Transaction ID']) & (sales_clean.index != i)].index

    sales_clean.loc[drinkRow, 'Modifiers Applied'] = sales_clean.loc[drinkRow, 'Modifiers Applied'].fillna('') + ", Extra shot"

    gSale = sales_clean.loc[i, 'Gross Sales']
    discount = sales_clean.loc[i, 'Discounts']
    nSale = sales_clean.loc[i, 'Net Sales']

    sales_clean.loc[drinkRow, 'Gross Sales'] += gSale
    sales_clean.loc[drinkRow, 'Discounts'] += discount
    sales_clean.loc[drinkRow, 'Net Sales'] += nSale

sales_clean = sales_clean.drop(index=sales_clean[sales_clean['Item'] == 'Extra shot'].index)


# Fixing cappuccino
sales_clean.loc[sales_clean['Item'] == "Capuccino", "Item"] = "Cappuccino"

Latte
Coffee
Tea
Capuccino
Americano
Espresso
Hot chocolate
Flat White
Chai Latte
Extra shot
Kind Bar
Mocha
Lemonade
Steamer
Dirty Chai
Cold Brew
Macchiato
3 cookie deal
Sticker
Hot Chocolate
Beanie
Cortado
Cookie
2 cookie deal
Tshirt
Cappuccino
Matcha Latte
Affogato
Cafe Au Lait
LiaP Cookie
Taos Bar
Affagado
London Fog
Red Eye
Catholic Flames Shirt
T-shirt
Pullover
Travel Mug
Hot Chocolate
Tote bag
Pullover Sweater
Hot Cocoa
Matcha lemonade
Cap
Breve Special
Soda
Flowers

In [895]:
# Time to make milk, syrup, to go/here, sweet/regular columns!
#for i in sales_clean["Modifiers Applied"].unique(): #
#    print(i)

#To go/Here
sales_clean['To Go'] = np.where(sales_clean['Modifiers Applied'].str.contains("Here", case=False, na=False), False, True)
sales_clean.tail(50)


# Milk types
milk_types = ['Oat', 'Almond', 'Soy', 'Coconut', 'Half&Half', 'Whole']

conditions = [sales_clean['Modifiers Applied'].str.contains(milk, case=False, na=False) for milk in milk_types]
choices = milk_types

sales_clean['Milk'] = np.select(conditions, choices, default='Whole') # default is Whole since baristas won't select whole if thats what customer wants
#sales_clean['Milk'].unique() #['Unknown', 'Whole', 'Oat', 'Almond', 'Soy', 'Coconut'] 
sales_clean.loc[sales_clean['Item'] == "Breve Special", 'Milk'] = 'Half&Half'

#Cafe vs Decaf

cafe_type = ['Decaf', 'Half-Caf' ,'Cafe']
conditions = [sales_clean['Modifiers Applied'].str.contains(sweet, case = False, na = False) for sweet in cafe_type]
choices = cafe_type
sales_clean["Caffeine"] = np.select(conditions, choices, default = 'Cafe')

# Sweet/Regular
sweet_type = ['Regular', 'Sweet']
conditions = [sales_clean['Modifiers Applied'].str.contains(sweet, case = False, na = False) for sweet in sweet_type]
choices = sweet_type
sales_clean["Sweetness"] = np.select(conditions, choices, default = 'Regular')

# Syrup
syrup_types = ['Vanilla', 'Lavender', 'Hazelnut', 'Strawberry', 'Rose', 'Ube', 'Pistachio', 'Peppermint', 'Gingerbread', 'Pumpkin', 'Apple', 'Sugar cookie', 'Ganache', 'Miel',  'Cor De Hanoi', 'S\'mores']
conditions = [sales_clean['Modifiers Applied'].str.contains(syrup, case = False, na = False) for syrup in syrup_types]
choices = syrup_types
sales_clean['Syrup'] = np.select(conditions, choices, default="NA")

sales_clean['Syrup'].value_counts() # 32057 Nas thats concerning but theres some syrups i have to hard code

sales_clean.loc[(sales_clean['Item'] == 'Hot Chocolate') | (sales_clean['Item'] == 'Mocha'), 'Syrup'] = 'Ganache' # hot chocolate

sales_clean.loc[(sales_clean['Item'] == 'London Fog'), 'Syrup'] = 'Vanilla' # London Fog

In [885]:
sales_clean["Syrup"].value_counts() 
"""
Syrup
NA              26629
Vanilla          7673
Ganache          4619
Lavender         2402
Pumpkin          1893
Hazelnut         1490
Gingerbread       990
Sugar cookie      662
Rose              442
Strawberry        428
Miel              308
Ube               257
Apple             256
Peppermint        254
S'mores           156
Pistachio         100
Cor De Hanoi       71
Name: count, dtype: int64

this counting non drinks too so i have to fix catagories
"""

"\nSyrup\nNA              26629\nVanilla          7673\nGanache          4619\nLavender         2402\nPumpkin          1893\nHazelnut         1490\nGingerbread       990\nSugar cookie      662\nRose              442\nStrawberry        428\nMiel              308\nUbe               257\nApple             256\nPeppermint        254\nS'mores           156\nPistachio         100\nCor De Hanoi       71\nName: count, dtype: int64\n\nthis counting non drinks too so i have to fix catagories\n"

In [886]:
for i in sales_clean['Item'].unique():
    print(i)

Latte
Coffee
Tea
Cappuccino
Americano
Espresso
Hot chocolate
Flat White
Chai Latte
Kind Bar
Mocha
Lemonade
Steamer
Dirty Chai
Cold Brew
Macchiato
3 cookie deal
Sticker
Hot Chocolate
Beanie
Cortado
Cookie
2 cookie deal
Tshirt
Matcha Latte
Affogato
Cafe Au Lait
LiaP Cookie
Taos Bar
Affagado
London Fog
Red Eye
Catholic Flames Shirt
T-shirt
Pullover
Travel Mug
Hot Chocolate
Tote bag
Pullover Sweater
Hot Cocoa
Matcha lemonade
Cap
Breve Special
Soda
Flowers

In [887]:
#   Spelling mistakes

sales_clean.loc[sales_clean["Item"] == "Hot chocolate", 'Item'] = "Hot Chocolate"
sales_clean.loc[sales_clean["Item"] == "Hot Chocolate ", 'Item'] = "Hot Chocolate"
sales_clean.loc[sales_clean["Item"] == "Hot Cocoa", 'Item'] = "Hot Chocolate"


sales_clean.loc[sales_clean['Item'] == "Affagado", "Item"] = "Affogato"

# sales_clean.loc[sales_clean['Item'].str.contains("cookie", case = False)]["Item"].unique() ['3 cookie deal', 'Cookie', '2 cookie deal', 'LiaP Cookie']
sales_clean.loc[sales_clean['Item'] == "3 cookie deal", "Count"] = 3
sales_clean.loc[sales_clean['Item'] == "3 cookie deal", "Item"] = "Cookie"

sales_clean.loc[sales_clean['Item'] == "2 cookie deal", "Count"] = 2
sales_clean.loc[sales_clean['Item'] == "2 cookie deal", "Item"] = "Cookie"

sales_clean.loc[sales_clean['Item'] == "LiaP Cookie", "Item"] = "Cookie"

In [888]:
sales_clean.loc[sales_clean['Item'] == "T-shirt", "Item"] = "Tshirt"
sales_clean.loc[sales_clean['Item'] == "Pullover Sweater", "Item"] = "Pullover"

In [889]:
sales_clean['Item'] = sales_clean['Item'].cat.remove_unused_categories()
for i in sales_clean["Item"].unique():
    print(i)

Latte
Coffee
Tea
Cappuccino
Americano
Espresso
Hot Chocolate
Flat White
Chai Latte
Kind Bar
Mocha
Lemonade
Steamer
Dirty Chai
Cold Brew
Macchiato
Cookie
Sticker
Beanie
Cortado
Tshirt
Matcha Latte
Affogato
Cafe Au Lait
Taos Bar
London Fog
Red Eye
Catholic Flames Shirt
Pullover
Travel Mug
Tote bag
Matcha lemonade
Cap
Breve Special
Soda
Flowers

In [ ]:
# Fixing catagories
sales_clean["Category"].unique() # ['Drinks', 'Espresso Drinks', NaN, 'Coffee Drinks', 'Teas', 'Food', 'Merch', 'Other Drinks']

espresso_drinks = ['Latte', 'Cappuccino', 'Americano', 'Espresso', 'Flat White',
                    'Mocha', 'Dirty Chai', 'Macchiato', 'Affogato', 'Cortado',
                    'Cafe Au Lait', 'Red Eye', 'Breve Special']

food_items = ['Kind Bar', 'Cookie', 'Taos Bar', 'Baked good']

merch_items = ['Sticker', 'Beanie', 'Tshirt', 'Pullover', 'Travel Mug', 'Tote bag',
               'Catholic Flames Shirt', 'Flowers', 'Cap']

non_espresso_drinks = ['Coffee', 'Chai Latte','Matcha Latte','Tea', 'Hot Chocolate', 'Lemonade', 'Steamer', 'Cold Brew',
                        'London Fog', 'Matcha lemonade', 'Soda']

conditions = [
    sales_clean['Item'].isin(espresso_drinks),
    sales_clean['Item'].isin(food_items),
    sales_clean['Item'].isin(merch_items),
    sales_clean['Item'].isin(non_espresso_drinks),
]
choices = ['Espresso Drinks', 'Food', 'Merch', 'Non-Espresso Drinks']

sales_clean['Category'] = np.select(conditions, choices, default='CHECK')

sales_clean[sales_clean['Category'] == "CHECK"] #everything falls into a catagory

Empty DataFrame
Columns: [Date, Time, Category, Item, Modifiers Applied, Gross Sales, Discounts, Net Sales, Transaction ID, Notes, Count, Token, PAN Suffix, Temp, Milk, To Go, Syrup, Caffeine, Sweetness]
Index: []

In [898]:
sales_clean.shape

(48490, 19)